services:
  server:
    image: "eeditor-server"
    container_name: "eeditor-server"
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80"
      - "443:443"
    volumes:
      - "/home/cstrpd/paomg:/var/www/html"
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
